type Theme =
  | "juejin"
  | "github"
  | "smartblue"
  | "cyanosis"
  | "channing-cyan"
  | "fancy"
  | "hydrogen"
  | "condensed-night-purple"
  | "greenwillow"
  | "v-green"
  | "vue-pro"
  | "healer-readable"
  | "mk-cute"
  | "jzman"
  | "geek-black"
  | "awesome-green"
  | "qklhk-chocolate"
  | "orange"
  | "scrolls-light"
  | "simplicity-green"
  | "arknights"
  | "vuepress"
  | "Chinese-red"
  | "nico"
  | "devui-blue";

export default Theme;
